import React from 'react';

export default function TrendReasonCard({ reason, loading, error }) {
  if (!reason && !loading && !error) return null;

  return (
    <div className="glass-card animate-fade-in-up-delay-5 mt-6 border-l-4 border-l-accent">
      <h3 className="text-lg font-bold text-navy-100 mb-4 flex items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
        今日走向分析 (AI)
      </h3>

      <div className="p-4 rounded-xl bg-navy-800/30 border border-navy-700/20">
        {loading ? (
          <div className="space-y-3">
            <div className="h-4 bg-navy-700/50 rounded-full animate-pulse w-3/4"></div>
            <div className="h-4 bg-navy-700/50 rounded-full animate-pulse w-full"></div>
            <div className="h-4 bg-navy-700/50 rounded-full animate-pulse w-5/6"></div>
            <div className="text-xs text-navy-400 mt-4 flex items-center gap-2">
              <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-accent" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              正在統整最新新聞與股價表現，請稍候...
            </div>
          </div>
        ) : error ? (
          <div className="flex items-start gap-3">
             <div className="w-8 h-8 rounded-full bg-red-500/10 flex items-center justify-center shrink-0">
               <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                 <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
               </svg>
             </div>
             <p className="text-sm text-red-300/80 leading-relaxed pt-1.5">{error}</p>
          </div>
        ) : (
          <div className="flex items-start gap-3">
             <div className="w-8 h-8 rounded-full bg-accent/10 flex items-center justify-center shrink-0 mt-1">
               <span className="text-xl">🤖</span>
             </div>
             <div className="text-sm text-navy-100 leading-relaxed pt-1.5 whitespace-pre-line text-justify">
               {reason}
             </div>
          </div>
        )}
      </div>
      
      {!loading && !error && (
        <div className="mt-3 text-right">
          <span className="text-[10px] text-navy-500">✨ Generated by AI (Google Gemini)</span>
        </div>
      )}
    </div>
  );
}
